# Generated by Django 5.0.6 on 2024-06-26 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=50)),
                ('company_description', models.TextField()),
                ('role_description', models.TextField()),
                ('qualification', models.TextField()),
                ('Experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myapp.jobdescription')),
            ],
        ),
    ]
